name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Bump version and push tag
      id: bumper
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_BUMP: patch
        WITH_V: false
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up buildx
      uses: docker/setup-buildx-action@v1.6.0
      with:
        install: true
    - name: Docker Login
      uses: docker/login-action@v1.12.0
      with:
        # Server address of Docker registry. If not set then will default to Docker Hub
        registry: quay.io
        # Username used to log against the Docker registry
        username: ${{ secrets.QUAY_IO_USERNAME }}
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.QUAY_IO_PASSWORD }}
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        # list of Docker images to use as base name for tags
        images: quay.io/edward_cooke/objectmirror
        tags: |
          type=schedule
          type=ref,event=branch
          type=ref,event=pr
          type=raw,value=${{ steps.bumper.outputs.new_tag }}
          type=raw,value=latest,enable=${{ github.event_name != 'pull_request' }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: src/Vecc.Kubernetes.ObjectMirror/Dockerfile
        labels: ${{ steps.meta.outputs.labels }}
        platforms: linux/amd64 #,linux/arm64
        push: false # ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
    - name: Update deployment.yaml
      uses: actions/github-script@v5.0.0
      if: ${{ github.event_name != 'pull_request' }}
      with:
        script: |
          sed -i -r 's@objectmirror:.*@objectmirror:2.2.2@' deployment.yaml
          git config --global --add user.email edward@frakkingsweet.com
          git config --global --add user.name GitBot
          git add -A
          git commit -m "[Skip] Version bump to ${{ steps.bumper.outputs.new_tag }}"
          git push origin
        
